[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "streamlit-drawable-canvas>=0.9.3",
    "streamlit>=1.47.1",
    "numpy>=2.3.2",
]
